# Generated by Django 2.0.1 on 2018-02-14 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20180131_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpartyrole',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='partyroleassociation',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
