# Generated by Django 2.0.1 on 2018-01-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('iso2_code', models.CharField(blank=True, max_length=2)),
                ('iso_numeric', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeographicArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('land_mass', models.CharField(blank=True, choices=[('North Island', 'North Island'), ('South Island', 'South Island')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('postcode', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, choices=[('Rural', 'Rural'), ('Urban', 'Urban')], max_length=50)),
                ('address_line1', models.CharField(blank=True, max_length=250, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoBoxAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('land_mass', models.CharField(blank=True, choices=[('North Island', 'North Island'), ('South Island', 'South Island')], max_length=50)),
                ('box_number', models.CharField(blank=True, max_length=200)),
                ('locality', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuralPropertyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('land_mass', models.CharField(blank=True, choices=[('North Island', 'North Island'), ('South Island', 'South Island')], max_length=50)),
                ('street_name', models.CharField(blank=True, max_length=200)),
                ('postcode', models.CharField(blank=True, max_length=50)),
                ('locality', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuralPropertySubAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('land_mass', models.CharField(blank=True, choices=[('North Island', 'North Island'), ('South Island', 'South Island')], max_length=50)),
                ('private_street_name', models.CharField(blank=True, max_length=150, null=True)),
                ('sub_unit_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_unit_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UrbanPropertyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('land_mass', models.CharField(blank=True, choices=[('North Island', 'North Island'), ('South Island', 'South Island')], max_length=50)),
                ('locality', models.CharField(blank=True, max_length=200)),
                ('postcode', models.CharField(blank=True, max_length=50)),
                ('street_name', models.CharField(blank=True, max_length=200)),
                ('street_number_first', models.IntegerField(blank=True, null=True)),
                ('street_number_first_suffix', models.CharField(blank=True, max_length=20)),
                ('street_number_last', models.IntegerField(blank=True, null=True)),
                ('street_number_last_suffix', models.CharField(blank=True, max_length=20)),
                ('street_suffix', models.CharField(blank=True, max_length=50)),
                ('street_type', models.CharField(blank=True, max_length=100)),
                ('line1', models.CharField(blank=True, max_length=150, null=True)),
                ('line2', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UrbanPropertySubAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('land_mass', models.CharField(blank=True, choices=[('North Island', 'North Island'), ('South Island', 'South Island')], max_length=50)),
                ('level_number', models.CharField(blank=True, max_length=20, null=True)),
                ('level_type', models.CharField(blank=True, max_length=50, null=True)),
                ('private_street_name', models.CharField(blank=True, max_length=150, null=True)),
                ('sub_unit_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_unit_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
