from distutils.core import setup
setup(name='cbe',
      version='0.3-alpha',
      py_modules=[
          'cbe.business_interaction.__init__',
          'cbe.business_interaction.admin',
          'cbe.business_interaction.models',
          'cbe.business_interaction.serializers',
          'cbe.business_interaction.tests',
          'cbe.business_interaction.views',
          'cbe.customer.__init__',
          'cbe.customer.admin',
          'cbe.customer.models',
          'cbe.customer.serializers',
          'cbe.customer.tests',
          'cbe.customer.views',
          'cbe.location.__init__',
          'cbe.location.admin',
          'cbe.location.models',
          'cbe.location.serializers',
          'cbe.location.tests',
          'cbe.location.views',
          'cbe.party.__init__',
          'cbe.party.admin',
          'cbe.party.models',
          'cbe.party.serializers',
          'cbe.party.views',
          'cbe.party.tests',
          'cbe.utils.serializer_fields', 'cbe.utils.serializers', 'cbe.utils.permissions', 'cbe.utils.api',
          'cbe.urls', 'cbe.tests', 'cbe.views', 'cbe.settings',
      ],
      )
