# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('party', '0006_auto_20170619_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('party_object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IdentificationType',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('party_object_id', models.PositiveIntegerField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation')),
                ('party_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_resources_staff_ownership', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='identification',
            name='identification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.IdentificationType'),
        ),
        migrations.AddField(
            model_name='identification',
            name='party_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_resources_identification_ownership', to='contenttypes.ContentType'),
        ),
    ]
