# Generated by Django 2.1.7 on 2019-02-23 03:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0004_auto_20180215_0942'),
        ('resource', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=200)),
                ('pin', models.CharField(blank=True, max_length=50, null=True)),
                ('party_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('party_role_object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IdentificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.LogicalResource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='party.Organisation')),
                ('email_contacts', models.ManyToManyField(blank=True, related_name='human_resources_staff_email_contacts', to='party.EmailContact')),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Individual')),
                ('logical_resources', models.ManyToManyField(blank=True, related_name='human_resources_staff_logical_resources', to='resource.LogicalResource')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation')),
                ('physical_contacts', models.ManyToManyField(blank=True, related_name='human_resources_staff_physical_contacts', to='party.PhysicalContact')),
                ('physical_resources', models.ManyToManyField(blank=True, related_name='human_resources_staff_physical_resources', to='resource.PhysicalResource')),
                ('telephone_numbers', models.ManyToManyField(blank=True, related_name='human_resources_staff_telephone_numbers', to='party.TelephoneNumber')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('notes', models.TextField(blank=True)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entries', to='human_resources.Timesheet')),
            ],
        ),
        migrations.AddField(
            model_name='identification',
            name='identification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.IdentificationType'),
        ),
        migrations.AddField(
            model_name='identification',
            name='party_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='human_resources_identification_party_identifiers', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='identification',
            name='party_role_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='human_resources_identification_party_role_identifiers', to='contenttypes.ContentType'),
        ),
    ]
