# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='association_type',
            field=models.CharField(default='undefined', max_length=200),
            preserve_default=False,
        ),
    ]
