# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resources', '0001_initial'),
        ('party', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='staff',
            name='party_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_resources_staff_ownership', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='identificationtype',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='identification',
            name='identification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.IdentificationType'),
        ),
        migrations.AddField(
            model_name='identification',
            name='party_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_resources_identification_ownership', to='contenttypes.ContentType'),
        ),
    ]
