# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_auto_20170802_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='identification',
            name='pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
