# Generated by Django 2.0.1 on 2018-01-31 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
        ('party', '0002_auto_20180131_1525'),
        ('human_resources', '0002_auto_20180131_1525'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='logical_resources',
            field=models.ManyToManyField(blank=True, related_name='human_resources_staff_logical_resources', to='resource.LogicalResource'),
        ),
        migrations.AddField(
            model_name='staff',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='staff',
            name='physical_contacts',
            field=models.ManyToManyField(blank=True, related_name='human_resources_staff_physical_contacts', to='party.PhysicalContact'),
        ),
        migrations.AddField(
            model_name='staff',
            name='physical_resources',
            field=models.ManyToManyField(blank=True, related_name='human_resources_staff_physical_resources', to='resource.PhysicalResource'),
        ),
        migrations.AddField(
            model_name='staff',
            name='telephone_numbers',
            field=models.ManyToManyField(blank=True, related_name='human_resources_staff_telephone_numbers', to='party.TelephoneNumber'),
        ),
        migrations.AddField(
            model_name='identificationtype',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='identificationtype',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.LogicalResource'),
        ),
        migrations.AddField(
            model_name='identification',
            name='identification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.IdentificationType'),
        ),
        migrations.AddField(
            model_name='identification',
            name='party_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='human_resources_identification_party_identifiers', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='identification',
            name='party_role_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='human_resources_identification_party_role_identifiers', to='contenttypes.ContentType'),
        ),
    ]
