# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_auto_20170811_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identification',
            name='party_content_type',
        ),
        migrations.RemoveField(
            model_name='identification',
            name='party_object_id',
        ),
        migrations.AddField(
            model_name='identification',
            name='valid_from',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='identification',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='identifiers',
            field=models.ManyToManyField(blank=True, to='human_resources.Identification'),
        ),
    ]
