# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_auto_20171214_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
