# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_identification_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identification',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='identificationtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['id']},
        ),
    ]
