# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_remove_staff_association_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='contact_mediums',
        ),
    ]
