# Generated by Django 2.0.1 on 2018-02-14 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_auto_20180214_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
