# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('human_resources', '0004_auto_20171117_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='identifiers',
        ),
        migrations.AddField(
            model_name='identification',
            name='party_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='human_resources_identification_ownership', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='identification',
            name='party_object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
