# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0006_timesheet_timesheetentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entries', to='human_resources.Timesheet'),
        ),
    ]
