# Generated by Django 2.0.1 on 2018-01-31 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_receivable', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerAccount'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_receivable.PaymentChannel'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
