# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalresource',
            old_name='physcial_objects',
            new_name='physical_objects',
        ),
    ]
