# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
