# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_partner', '0002_auto_20170606_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='association_type',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='association_type',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='association_type',
        ),
    ]
