# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_partner', '0002_auto_20170828_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAccount',
            fields=[
                ('created', models.DateField(auto_now_add=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('account_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('account_status', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=300)),
                ('pin', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_accounts', to='supplier_partner.Supplier')),
            ],
        ),
    ]
