# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20170815_1129'),
        ('party', '0003_auto_20171117_1411'),
        ('supplier_partner', '0004_auto_20171117_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='email_contacts',
            field=models.ManyToManyField(blank=True, related_name='supplier_partner_buyer_email_contacts', to='party.EmailContact'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='logical_resources',
            field=models.ManyToManyField(blank=True, related_name='supplier_partner_buyer_logical_resources', to='resource.LogicalResource'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='physical_contacts',
            field=models.ManyToManyField(blank=True, related_name='supplier_partner_buyer_physical_contacts', to='party.PhysicalContact'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='physical_resources',
            field=models.ManyToManyField(blank=True, related_name='supplier_partner_buyer_physical_resources', to='resource.PhysicalResource'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='telephone_numbers',
            field=models.ManyToManyField(blank=True, related_name='supplier_partner_buyer_telephone_numbers', to='party.TelephoneNumber'),
        ),
        migrations.AddField(
            model_name='partner',
            name='email_contacts',
            field=models.ManyToManyField(blank=True, related_name='supplier_partner_partner_email_contacts', to='party.EmailContact'),
        ),
        migrations.AddField(
            model_name='partner',
            name='logical_resources',
            field=models.ManyToManyField(blank=True, related_name='supplier_partner_partner_logical_resources', to='resource.LogicalResource'),
        ),
        migrations.AddField(
            model_name='partner',
            name='physical_contacts',
            field=models.ManyToManyField(blank=True, related_name='supplier_partner_partner_physical_contacts', to='party.PhysicalContact'),
        ),
        migrations.AddField(
            model_name='partner',
            name='physical_resources',
            field=models.ManyToManyField(blank=True, related_name='supplier_partner_partner_physical_resources', to='resource.PhysicalResource'),
        ),
        migrations.AddField(
            model_name='partner',
            name='telephone_numbers',
            field=models.ManyToManyField(blank=True, related_name='supplier_partner_partner_telephone_numbers', to='party.TelephoneNumber'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email_contacts',
            field=models.ManyToManyField(blank=True, related_name='supplier_partner_supplier_email_contacts', to='party.EmailContact'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='logical_resources',
            field=models.ManyToManyField(blank=True, related_name='supplier_partner_supplier_logical_resources', to='resource.LogicalResource'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='physical_contacts',
            field=models.ManyToManyField(blank=True, related_name='supplier_partner_supplier_physical_contacts', to='party.PhysicalContact'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='physical_resources',
            field=models.ManyToManyField(blank=True, related_name='supplier_partner_supplier_physical_resources', to='resource.PhysicalResource'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='telephone_numbers',
            field=models.ManyToManyField(blank=True, related_name='supplier_partner_supplier_telephone_numbers', to='party.TelephoneNumber'),
        ),
    ]
