# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('information_technology', '0002_auto_20170721_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='processes',
            field=models.ManyToManyField(blank=True, related_name='projects', to='information_technology.Process'),
        ),
    ]
