# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_technology', '0002_auto_20170713_1453'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='components', to='information_technology.Component'),
        ),
    ]
