# Generated by Django 2.0.1 on 2018-01-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information_technology', '0002_auto_20180131_1525'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='processes',
            field=models.ManyToManyField(blank=True, related_name='projects', to='information_technology.Process'),
        ),
    ]
