# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit', '0001_initial'),
        ('customer', '0001_initial'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditprofile',
            name='credit_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='creditprofile',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='creditbalanceevent',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerAccount'),
        ),
        migrations.AddField(
            model_name='creditbalanceevent',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.Credit'),
        ),
        migrations.AddField(
            model_name='creditbalanceevent',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='creditalert',
            name='credit_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='creditalert',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='creditalert',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.CreditProfile'),
        ),
        migrations.AddField(
            model_name='credit',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerAccount'),
        ),
        migrations.AddField(
            model_name='credit',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='credit',
            name='liability_ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_liabilities', to='party.Organisation'),
        ),
    ]
