# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_object', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='floor_square_metres',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
