# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical_object', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['id']},
        ),
    ]
