# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('customer_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('customer_status', models.CharField(choices=[('new', 'new'), ('active', 'active'), ('inactive', 'inactive'), ('prospective', 'prospective')], max_length=100)),
            ],
            options={
                'ordering': ['customer_number'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('created', models.DateField(auto_now_add=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('account_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('account_status', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=300)),
                ('pin', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAccountContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAccountRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('relationship_type', models.CharField(max_length=200)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from_account', to='customer.CustomerAccount')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to_account', to='customer.CustomerAccount')),
            ],
        ),
    ]
