# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccountcontact',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Individual'),
        ),
        migrations.AddField(
            model_name='customeraccountcontact',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='customer_account_contact',
            field=models.ManyToManyField(blank=True, to='customer.CustomerAccountContact'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='liability_ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_liabilities', to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_managed', to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Individual'),
        ),
        migrations.AddField(
            model_name='customer',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manages_customers', to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
    ]
