# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20170802_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='credit_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='credit_status',
            field=models.CharField(choices=[('active', 'active'), ('stop', 'stop')], default='active', max_length=100),
            preserve_default=False,
        ),
    ]
