# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20170606_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='association_type',
        ),
        migrations.RemoveField(
            model_name='customeraccountcontact',
            name='association_type',
        ),
    ]
