# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20170811_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='customer_account_contact',
            field=models.ManyToManyField(blank=True, related_name='customer_accounts', to='customer.CustomerAccountContact'),
        ),
    ]
