# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20170804_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
