# Generated by Django 2.0.1 on 2018-02-14 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180131_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='customeraccountcontact',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
