# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20170606_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_mediums',
        ),
        migrations.RemoveField(
            model_name='customeraccountcontact',
            name='contact_mediums',
        ),
    ]
