# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20170815_1129'),
        ('party', '0002_auto_20171117_1346'),
        ('customer', '0005_auto_20171117_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_contacts',
            field=models.ManyToManyField(blank=True, related_name='customer_customer_email_contacts', to='party.EmailContact'),
        ),
        migrations.AddField(
            model_name='customer',
            name='logical_resources',
            field=models.ManyToManyField(blank=True, related_name='customer_customer_logical_resources', to='resource.LogicalResource'),
        ),
        migrations.AddField(
            model_name='customer',
            name='physical_contacts',
            field=models.ManyToManyField(blank=True, related_name='customer_customer_physical_contacts', to='party.PhysicalContact'),
        ),
        migrations.AddField(
            model_name='customer',
            name='physical_resources',
            field=models.ManyToManyField(blank=True, related_name='customer_customer_physical_resources', to='resource.PhysicalResource'),
        ),
        migrations.AddField(
            model_name='customer',
            name='telephone_numbers',
            field=models.ManyToManyField(blank=True, related_name='customer_customer_telephone_numbers', to='party.TelephoneNumber'),
        ),
        migrations.AddField(
            model_name='customeraccountcontact',
            name='email_contacts',
            field=models.ManyToManyField(blank=True, related_name='customer_customeraccountcontact_email_contacts', to='party.EmailContact'),
        ),
        migrations.AddField(
            model_name='customeraccountcontact',
            name='logical_resources',
            field=models.ManyToManyField(blank=True, related_name='customer_customeraccountcontact_logical_resources', to='resource.LogicalResource'),
        ),
        migrations.AddField(
            model_name='customeraccountcontact',
            name='physical_contacts',
            field=models.ManyToManyField(blank=True, related_name='customer_customeraccountcontact_physical_contacts', to='party.PhysicalContact'),
        ),
        migrations.AddField(
            model_name='customeraccountcontact',
            name='physical_resources',
            field=models.ManyToManyField(blank=True, related_name='customer_customeraccountcontact_physical_resources', to='resource.PhysicalResource'),
        ),
        migrations.AddField(
            model_name='customeraccountcontact',
            name='telephone_numbers',
            field=models.ManyToManyField(blank=True, related_name='customer_customeraccountcontact_telephone_numbers', to='party.TelephoneNumber'),
        ),
    ]
