# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20170619_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercreditprofile',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='place_content_type',
        ),
        migrations.RemoveField(
            model_name='customerorderitem',
            name='business_interaction_content_type',
        ),
        migrations.RemoveField(
            model_name='customerorderitem',
            name='place_content_type',
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='CustomerCreditProfile',
        ),
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
        migrations.DeleteModel(
            name='CustomerOrderItem',
        ),
    ]
