# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20171117_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='identifiers',
        ),
        migrations.RemoveField(
            model_name='customeraccountcontact',
            name='identifiers',
        ),
    ]
