# Generated by Django 2.0.1 on 2018-02-14 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
