# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20171214_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='geographic_address_content_type',
        ),
        migrations.RemoveField(
            model_name='location',
            name='geographic_address_object_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='position_number',
        ),
        migrations.RemoveField(
            model_name='location',
            name='type',
        ),
        migrations.RemoveField(
            model_name='location',
            name='x',
        ),
        migrations.RemoveField(
            model_name='location',
            name='y',
        ),
        migrations.RemoveField(
            model_name='location',
            name='z',
        ),
        migrations.RemoveField(
            model_name='poboxaddress',
            name='state_or_province',
        ),
        migrations.RemoveField(
            model_name='ruralpropertyaddress',
            name='state_or_province',
        ),
        migrations.RemoveField(
            model_name='ruralpropertysubaddress',
            name='state_or_province',
        ),
        migrations.RemoveField(
            model_name='urbanpropertyaddress',
            name='state_or_province',
        ),
        migrations.RemoveField(
            model_name='urbanpropertysubaddress',
            name='state_or_province',
        ),
        migrations.AddField(
            model_name='location',
            name='address_type',
            field=models.CharField(blank=True, choices=[('RuralPropertyAddress', 'RuralPropertyAddress'), ('UrbanPropertyAddress', 'UrbanPropertyAddress')], max_length=150),
        ),
        migrations.AddField(
            model_name='location',
            name='rural_property_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.RuralPropertyAddress'),
        ),
        migrations.AddField(
            model_name='location',
            name='urban_property_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.UrbanPropertyAddress'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='poboxaddress',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Province'),
        ),
        migrations.AddField(
            model_name='ruralpropertyaddress',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Province'),
        ),
        migrations.AddField(
            model_name='ruralpropertysubaddress',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Province'),
        ),
        migrations.AddField(
            model_name='urbanpropertyaddress',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Province'),
        ),
        migrations.AddField(
            model_name='urbanpropertysubaddress',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Province'),
        ),
    ]
