# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20171222_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address_type',
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.City'),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Country'),
        ),
        migrations.AddField(
            model_name='location',
            name='land_mass',
            field=models.CharField(blank=True, choices=[('North Island', 'North Island'), ('South Island', 'South Island')], max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='postcode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Province'),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, choices=[('Rural', 'Rural'), ('Urban', 'Urban')], max_length=50),
        ),
        migrations.AddField(
            model_name='poboxaddress',
            name='land_mass',
            field=models.CharField(blank=True, choices=[('North Island', 'North Island'), ('South Island', 'South Island')], max_length=50),
        ),
        migrations.AddField(
            model_name='ruralpropertyaddress',
            name='land_mass',
            field=models.CharField(blank=True, choices=[('North Island', 'North Island'), ('South Island', 'South Island')], max_length=50),
        ),
        migrations.AddField(
            model_name='ruralpropertysubaddress',
            name='land_mass',
            field=models.CharField(blank=True, choices=[('North Island', 'North Island'), ('South Island', 'South Island')], max_length=50),
        ),
        migrations.AddField(
            model_name='urbanpropertyaddress',
            name='land_mass',
            field=models.CharField(blank=True, choices=[('North Island', 'North Island'), ('South Island', 'South Island')], max_length=50),
        ),
        migrations.AddField(
            model_name='urbanpropertysubaddress',
            name='land_mass',
            field=models.CharField(blank=True, choices=[('North Island', 'North Island'), ('South Island', 'South Island')], max_length=50),
        ),
    ]
