# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20171222_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ruralpropertyaddress',
            name='line1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ruralpropertyaddress',
            name='line2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='urbanpropertyaddress',
            name='line1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='urbanpropertyaddress',
            name='line2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
