# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20180119_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruralpropertyaddress',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='ruralpropertyaddress',
            name='line2',
        ),
        migrations.AddField(
            model_name='location',
            name='address_line1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='address_line2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
