# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericpartyrole',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='partyroleassociation',
            options={'ordering': ['id']},
        ),
    ]
