# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_auto_20171117_1346'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpartyrole',
            name='identifiers',
            field=models.ManyToManyField(blank=True, to='human_resources.Identification'),
        ),
        migrations.AddField(
            model_name='owner',
            name='identifiers',
            field=models.ManyToManyField(blank=True, to='human_resources.Identification'),
        ),
    ]
