# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20170815_1129'),
        ('party', '0002_auto_20171117_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcontact',
            name='party_role_content_type',
        ),
        migrations.RemoveField(
            model_name='emailcontact',
            name='party_role_object_id',
        ),
        migrations.RemoveField(
            model_name='physicalcontact',
            name='party_role_content_type',
        ),
        migrations.RemoveField(
            model_name='physicalcontact',
            name='party_role_object_id',
        ),
        migrations.RemoveField(
            model_name='telephonenumber',
            name='party_role_content_type',
        ),
        migrations.RemoveField(
            model_name='telephonenumber',
            name='party_role_object_id',
        ),
        migrations.AddField(
            model_name='genericpartyrole',
            name='email_contacts',
            field=models.ManyToManyField(blank=True, related_name='party_genericpartyrole_email_contacts', to='party.EmailContact'),
        ),
        migrations.AddField(
            model_name='genericpartyrole',
            name='logical_resources',
            field=models.ManyToManyField(blank=True, related_name='party_genericpartyrole_logical_resources', to='resource.LogicalResource'),
        ),
        migrations.AddField(
            model_name='genericpartyrole',
            name='physical_contacts',
            field=models.ManyToManyField(blank=True, related_name='party_genericpartyrole_physical_contacts', to='party.PhysicalContact'),
        ),
        migrations.AddField(
            model_name='genericpartyrole',
            name='physical_resources',
            field=models.ManyToManyField(blank=True, related_name='party_genericpartyrole_physical_resources', to='resource.PhysicalResource'),
        ),
        migrations.AddField(
            model_name='genericpartyrole',
            name='telephone_numbers',
            field=models.ManyToManyField(blank=True, related_name='party_genericpartyrole_telephone_numbers', to='party.TelephoneNumber'),
        ),
        migrations.AddField(
            model_name='owner',
            name='email_contacts',
            field=models.ManyToManyField(blank=True, related_name='party_owner_email_contacts', to='party.EmailContact'),
        ),
        migrations.AddField(
            model_name='owner',
            name='logical_resources',
            field=models.ManyToManyField(blank=True, related_name='party_owner_logical_resources', to='resource.LogicalResource'),
        ),
        migrations.AddField(
            model_name='owner',
            name='physical_contacts',
            field=models.ManyToManyField(blank=True, related_name='party_owner_physical_contacts', to='party.PhysicalContact'),
        ),
        migrations.AddField(
            model_name='owner',
            name='physical_resources',
            field=models.ManyToManyField(blank=True, related_name='party_owner_physical_resources', to='resource.PhysicalResource'),
        ),
        migrations.AddField(
            model_name='owner',
            name='telephone_numbers',
            field=models.ManyToManyField(blank=True, related_name='party_owner_telephone_numbers', to='party.TelephoneNumber'),
        ),
    ]
