# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20170601_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpartyrole',
            name='association_type',
            field=models.CharField(default='undefined', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='owner',
            name='association_type',
            field=models.CharField(default='undefined', max_length=200),
            preserve_default=False,
        ),
    ]
