# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_auto_20171214_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
