# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_auto_20171117_1411'),
        ('party', '0003_auto_20171117_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='identifiers',
            field=models.ManyToManyField(blank=True, to='human_resources.Identification'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='identifiers',
            field=models.ManyToManyField(blank=True, to='human_resources.Identification'),
        ),
    ]
