# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('party', '0003_auto_20170606_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyRoleAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('association_type', models.CharField(max_length=200)),
                ('association_from_object_id', models.PositiveIntegerField()),
                ('association_to_object_id', models.PositiveIntegerField()),
                ('association_from_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_partyroleassociation_from', to='contenttypes.ContentType')),
                ('association_to_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_partyroleassociation_to', to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='genericpartyrole',
            name='association_type',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='association_type',
        ),
    ]
