# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_auto_20170606_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontact',
            name='party_role_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_organisations', to='party.Organisation'),
        ),
        migrations.AlterField(
            model_name='physicalcontact',
            name='party_role_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='telephonenumber',
            name='party_role_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
