# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_auto_20171117_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericpartyrole',
            name='identifiers',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='identifiers',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='identifiers',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='identifiers',
        ),
    ]
