# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_auto_20170613_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericpartyrole',
            name='contact_mediums',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='contact_mediums',
        ),
    ]
