# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_auto_20170619_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyroleassociation',
            name='association_from_object_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='partyroleassociation',
            name='association_to_object_id',
            field=models.CharField(max_length=200),
        ),
    ]
