# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_technology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
