# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_technology', '0002_auto_20170721_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='processframework',
            name='id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
