# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_technology', '0002_auto_20170713_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentclassification',
            name='id',
        ),
        migrations.RemoveField(
            model_name='processclassification',
            name='id',
        ),
        migrations.RemoveField(
            model_name='processframework',
            name='id',
        ),
        migrations.AddField(
            model_name='processframework',
            name='documentation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='componentclassification',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='processclassification',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='processframework',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
