# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_technology', '0003_processframework_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processframework',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='processframework',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
