# Generated by Django 2.0.1 on 2018-01-31 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccountcontact',
            name='email_contacts',
            field=models.ManyToManyField(blank=True, related_name='customer_customeraccountcontact_email_contacts', to='party.EmailContact'),
        ),
        migrations.AddField(
            model_name='customeraccountcontact',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Individual'),
        ),
    ]
