# Generated by Django 2.0.1 on 2018-01-31 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
        ('customer', '0002_auto_20180131_1525'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccountcontact',
            name='logical_resources',
            field=models.ManyToManyField(blank=True, related_name='customer_customeraccountcontact_logical_resources', to='resource.LogicalResource'),
        ),
        migrations.AddField(
            model_name='customeraccountcontact',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='customeraccountcontact',
            name='physical_contacts',
            field=models.ManyToManyField(blank=True, related_name='customer_customeraccountcontact_physical_contacts', to='party.PhysicalContact'),
        ),
        migrations.AddField(
            model_name='customeraccountcontact',
            name='physical_resources',
            field=models.ManyToManyField(blank=True, related_name='customer_customeraccountcontact_physical_resources', to='resource.PhysicalResource'),
        ),
        migrations.AddField(
            model_name='customeraccountcontact',
            name='telephone_numbers',
            field=models.ManyToManyField(blank=True, related_name='customer_customeraccountcontact_telephone_numbers', to='party.TelephoneNumber'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_accounts', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='customer_account_contact',
            field=models.ManyToManyField(blank=True, related_name='customer_accounts', to='customer.CustomerAccountContact'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_managed', to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_contacts',
            field=models.ManyToManyField(blank=True, related_name='customer_customer_email_contacts', to='party.EmailContact'),
        ),
        migrations.AddField(
            model_name='customer',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Individual'),
        ),
        migrations.AddField(
            model_name='customer',
            name='logical_resources',
            field=models.ManyToManyField(blank=True, related_name='customer_customer_logical_resources', to='resource.LogicalResource'),
        ),
        migrations.AddField(
            model_name='customer',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manages_customers', to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='physical_contacts',
            field=models.ManyToManyField(blank=True, related_name='customer_customer_physical_contacts', to='party.PhysicalContact'),
        ),
        migrations.AddField(
            model_name='customer',
            name='physical_resources',
            field=models.ManyToManyField(blank=True, related_name='customer_customer_physical_resources', to='resource.PhysicalResource'),
        ),
        migrations.AddField(
            model_name='customer',
            name='telephone_numbers',
            field=models.ManyToManyField(blank=True, related_name='customer_customer_telephone_numbers', to='party.TelephoneNumber'),
        ),
    ]
